# Generated by Django 4.2.4 on 2023-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDjango',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='token', max_length=255, unique=True)),
                ('at_created', models.DateTimeField(db_column='at_created')),
            ],
            options={
                'verbose_name': 'token_django',
                'verbose_name_plural': 'tokens_django',
                'db_table': 'token_django',
            },
        ),
    ]
